/**
 * Scrum board API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Card {
    /**
     * this is the title
     */
    title: string;
    description: string;
    state: Card.StateEnum;
}
export class Card implements Card {
  constructor(public title: string, public description: string, public state: Card.StateEnum) {
  }
}
export namespace Card {
    export type StateEnum = 'to-do' | 'in-progress' | 'done';
    export const StateEnum = {
        ToDo: 'to-do' as StateEnum,
        InProgress: 'in-progress' as StateEnum,
        Done: 'done' as StateEnum
    };
}
