/**
 * Scrum board API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Card } from '../model/card';


@Injectable()
export class ApiService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();

    constructor(protected httpClient: HttpClient) {

    }



    /**
     * retrieves all cards
     *
     * @param state descriminate on the state of the card
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cardsGet(state?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Card>>;
    public cardsGet(state?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Card>>>;
    public cardsGet(state?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Card>>>;
    public cardsGet(state?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams();
        if (state !== undefined && state !== null) {
            queryParameters = queryParameters.set('state', <any>state);
        }

        let headers = this.defaultHeaders;
        headers = headers.set('Accept',  'application/json');


        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Card>>('get',`${this.basePath}/cards`,
            {
                params: queryParameters,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create a new Scrum card
     *
     * @param body the card to be created
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cardsPost(body: Card, observe?: 'body', reportProgress?: boolean): Observable<Card>;
    public cardsPost(body: Card, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Card>>;
    public cardsPost(body: Card, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Card>>;
    public cardsPost(body: Card, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling cardsPost.');
        }

        let headers = this.defaultHeaders;

        headers = headers.set('Accept', 'application/json');

        headers = headers.set('Content-Type', 'application/json');


        return this.httpClient.request<Card>('post',`${this.basePath}/cards`,
            {
                body: body,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
